import { Albert_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';

const albertSans = Albert_Sans({
  variable: '--font-albert',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${albertSans.variable} antialiased bg-[#F7EDE2] overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
