import { Albert_Sans } from 'next/font/google';
import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import Article from '@/components/Article';
import Main from '@/components/Main';

const albertSans = Albert_Sans({
  variable: '--font-albert',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${albertSans.variable} antialiased bg-[#F7EDE2]`}>
        <Header />
        <div className='grid grid-cols-12 gap-8 mx-[64px]'>
          <Article />
          <Main />
        </div>
        <div className='grid grid-cols-12 gap-8 mx-[64px] mt-9'>{children}</div>
      </body>
    </html>
  );
}
